name: omphalos_warehouse
version: 0.2.0
config-version: 2

profile: omphalos_warehouse

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  omphalos_warehouse:
    +materialized: view
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: view
