version: 2

sources:
  - name: raw
    description: Tables materialized by the reference pipeline.
    tables:
      - name: trade_feed
        columns:
          - name: shipment_id
            tests: [not_null, unique]
      - name: registry
        columns:
          - name: entity_id
            tests: [not_null, unique]
      - name: entity_matches
      - name: review_queue
      - name: entity_scores

models:
  - name: stg_trade_feed
    description: Canonical trade feed rows.
    columns:
      - name: shipment_id
        tests: [not_null, unique]
      - name: ship_date
        tests: [not_null]
      - name: value_usd
        tests: [not_null]

  - name: stg_registry
    description: Canonical entity registry rows.
    columns:
      - name: entity_id
        tests: [not_null, unique]

  - name: stg_entity_matches
    description: Shipment to entity match decisions.
    columns:
      - name: shipment_id
        tests: [not_null]
      - name: entity_id
        tests: [not_null]

  - name: stg_review_queue
    description: Review queue items with candidate lists.
    columns:
      - name: shipment_id
        tests: [not_null, unique]

  - name: stg_entity_scores
    description: Entity scores produced by the analytics stage.
    columns:
      - name: entity_id
        tests: [not_null]
