version: 2

sources:
  - name: omphalos
    schema: main
    tables:
      - name: trade_feed
      - name: registry
      - name: entity_matches
      - name: entity_scores

models:
  - name: stg_trade_feed
    columns:
      - name: shipment_id
        tests: [not_null, unique]
  - name: stg_registry
    columns:
      - name: entity_id
        tests: [not_null, unique]
  - name: stg_entity_matches
  - name: stg_entity_scores
